export { default as Google } from "./Google.png";
export { default as URL } from "./URL.png";
export { default as Upload } from "./Upload.png";
export { default as Thumb } from "./Thumb.png";
export { default as Favorite } from "./Favorite.png";
export { default as JPG } from "./JPG.png";
export { default as PNG } from "./PNG.png";
export { default as PDF } from "./PDF.png";
export { default as Clipboard } from "./Clipboard.png";
